name: ipbc
version: 0.11.1.0-1
summary: "IPBC"
description: |
    IPBC
grade: devel
confinement: strict

apps:
    ipbcd:
        daemon: forking
        command: |
          ipbcd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/ipbcd.conf
        plugs:
            - network
            - network-bind
    ipbc-wallet-rpc:
        command: |
          ipbc-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    ipbc-wallet-cli:
        command: |
          ipbc-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/ipbcd.conf: etc/ipbcd.conf
            contrib/snap/ipbcd-wrapper: bin/ipbcd-wrapper
        prime:
            - etc
            - bin
